apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-name
  name: node-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-name
  template:
    metadata:
      labels:
        app: node-name
    spec:
      nodeName: kind-worker
      containers:
      - image: nginx
        name: node-name
