apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-selector
  name: node-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-selector
  template:
    metadata:
      labels:
        app: node-selector
    spec:
      nodeSelector:
        beta.kubernetes.io/instance-type: r5.2xlarge
      containers:
      - image: nginx
        name: node-selector
