apiVersion: v1
kind: Pod
metadata:
  labels:
  name: redis
spec:
  containers:
  - name: redis-server
    image: redis:3.2-alpine
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  nodeSelector:
    beta.kubernetes.io/instance-type: r5.2xlarge
